# Generated by Django 5.0.4 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0002_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(null=True),
        ),
    ]
