# Generated by Django 5.0.4 on 2024-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0005_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(null=True),
        ),
    ]
