# Generated by Django 5.0.4 on 2024-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0012_alter_userprofile_backgroundimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
