# Generated by Django 5.0.4 on 2024-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0013_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="quote",
            field=models.CharField(blank=True, default="not qoute", max_length=255),
        ),
    ]
