# Generated by Django 5.0.4 on 2024-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0014_alter_userprofile_quote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="quote",
            new_name="qoute",
        ),
    ]
