# Generated by Django 5.0.4 on 2024-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmedia", "0015_rename_quote_userprofile_qoute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts", to="socialmedia.userprofile"
            ),
        ),
    ]
